description: "Analyzing overeducation in the UK for various demographics"
email: kyle@kyso.io
main: notebook.ipynb
preview: images/preview.png
title: "People in the UK are Overeducated for their Jobs"
