description: "Mapping where billionaires tend to migrate and the density of wealth in cities across the world."
email: kyle@kyso.io
main: notebook.ipynb
preview: images/preview.png
title: "Global Concentration of High Net Worth Individuals"
